[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
lib_deps =
    https://github.com/earlephilhower/BackgroundAudio/archive/refs/tags/1.4.4.zip
    https://github.com/olikraus/U8g2_for_Adafruit_GFX/archive/master.zip
    https://github.com/adafruit/Adafruit_SSD1306/archive/refs/heads/master.zip
build_flags = -O3
extra_scripts = pre:patchlib.py
; board_build.embed_files =
    ; data/hiragana.vlw

[env:cardputer]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
lib_deps =
    https://github.com/earlephilhower/BackgroundAudio/archive/refs/tags/1.4.4.zip
    m5stack/M5Cardputer@^1.1.1
build_flags = -O3 -DARDUINO_USB_CDC_ON_BOOT=1 -DCARDPUTER
extra_scripts = pre:patchlib.py
board_build.embed_files =
    data/hiragana.vlw